name: norminette

on:
  push:
    branches: $default-branch
  pull_request:
    branches: $default-branch

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies
      - run: pip install --upgrade norminette
      - run: norminette src/ include/ libft/ | grep -v OK...
